filter:
    excluded_paths:
        - 'vendor/*'
    paths:
        - 'library/*'
        - 'tests/*'

tools:
    php_cpd: true

    php_pdepend:
        excluded_dirs: [vendor]

    php_code_sniffer:
        enabled: true
        config:
            tab_width: 0
            standard: custom
            ruleset: CodingStandard

    external_code_coverage:
        timeout: 600